services:
  print-status:
    image: busybox
    command: 'sh -c ''echo -e "--------------------------------------------\n|                                          |\n|   App started: \"http://localhost:1337\"   |\n|                                          |\n--------------------------------------------"'''
    depends_on:
      - frontend

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile

    environment:
      - BACKEND_URL=http://backend:2137

    ports:
      - "1337:3000"

    depends_on:
      backend:
        condition: service_healthy

  backend:
    build:
      context: backend
      dockerfile: Dockerfile

    environment:
      - DATABASE_URL=postgresql+psycopg://arxivsearch:arxivsearch@postgres:5432/arxivsearch
      - ELASTIC_URL=http://elasticsearch:9200
      - DEBUG=1
      - LOGGER_LEVEL=10
      - CORS=http://localhost:3000

    ports:
      - "2137:2137"

    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5

    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: arxivsearch
      POSTGRES_PASSWORD: arxivsearch
      POSTGRES_DB: arxivsearch

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "arxivsearch"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 3s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      xpack.license.self_generated.type: basic
      node.name: elasticsearch

    ports:
      - "9200:9200"

    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 5

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     arxivsearch:
  #       condition: service_healthy

volumes:
  postgres_data:
    driver: local

  elasticsearch_data:
    driver: local
